version: "2.0"
services:
 reactweb:
  build:
   context: .
   dockerfile: Dockerfile.dev
  ports:
   - "3001:3000"
  volumes:
   - /app/node_modules
   - .:/app
 reacttest:
  build:
   context: .
   dockerfile: Dockerfile.dev
  volumes:
   - /app/node_modules
   - .:/app
  command: ["npm", "run", "test"] 
